import { allDocs, Doc } from 'contentlayer/generated';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';

interface Props {
  docs: Doc[];
}

export default function Home({ docs }: Props) {
  return (
    <div>
      <Head>
        <title>React Components</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex-grow px-10 py-5'>
        <h1 className='text-4xl text-primary mb-10'>React Components</h1>
        {docs.map(doc => {
          return (
            <Link key={doc._id} href={`/${doc.title}`}>
              <div className='mb-6 last:mb-0'>
                <h2 className='text-2xl mb-2'>{doc.title}</h2>
                <p>{doc.intro}</p>
              </div>
            </Link>
          );
        })}
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps<{ docs: Doc[] }> = () => {
  const docs = allDocs;

  return { props: { docs } };
};
